### ISSUE TITLE
`ComptimeStringMap` replaced with `StaticStringMap`

### ISSUE THREAD

**Issue by tomasz-lisowski** [ZigEmbeddedGroup/microzig#185]
https://github.com/ziglang/zig/pull/19719 replaced `ComptimeStringMap` with `StaticStringMap`.

**Comment by tomasz-lisowski** [comment]
I opened a pull request because simply replacing compiles for me without any obvious problems. Feel free to reject that pull request though.

https://github.com/ZigEmbeddedGroup/microzig/pull/186

**Comment by vesim987** [comment]
Fixed in #198
