### ISSUE TITLE
Usb.init_clk() freezes depending on timing

### ISSUE THREAD

**Issue by hryx** [ZigEmbeddedGroup/microzig#214]
I have been struggling to run USB device code, e.g. the HID demo, on any rp2040 board because the program always freezes in the call to `rp2040.usb.Usb.init_clk()`. However, @arkadiuszwojcik helped me debug tonight and found that it is possible to get it to work with a timing hack.

## Steps to reproduce

Modify the example `usb_hid.zig` around the clock initialization:

```zig
    ...
    std.log.debug("one", .{});
    // First we initialize the USB clock
    rp2040.usb.Usb.init_clk();
    std.log.debug("two", .{});
    ...
```

Run `zig build -Doptimize=ReleaseSmall`.

When flashing a Raspberry Pi Pico H or similar board, UART prints `one` but not `two`, and the LED never blinks.

Modify `bsp/raspberrypi/rp2040/src/hal/resets.zig` such that the empty while loop has at least one NOP instruction:

```zig
pub fn reset(mask: Mask) void {
    ...
    while ((RESETS.RESET_DONE.raw & raw_mask) != raw_mask) {
        asm volatile (
            \\ nop
        );
    }
}
```

...and suddenly, the LED blinks and we see `two` in the log. It also suffices to add some log lines inside `reset()` to change the timing of operations, although it may not be as consistent.

With `-Doptimize=Debug`, there is no issue with or without the `asm` block. With `ReleaseSmall`, it is as described above. With `ReleaseFast` and `ReleaseSafe`, I still get freezing even with the `asm` block.

## Other notes

As a reference point, the stock `pico-examples/usb/device/dev_hid_composite` example from Raspberry Pi / TinyUSB works out of the box for me.

The above findings are true both on main (bb88889) and based on #211.

**Comment by arkadiuszwojcik** [comment]
Few lines below there is simillar fix:

```
// have to bitcast after a read() instead of `RESETS.RESET_DONE.raw` due to
// some optimization bug. While loops will not be optimzed away if the
// condition has side effects like dereferencing a volatile pointer.
// It seems that volatile is not propagating correctly.
while (@as(u32, @bitCast(RESETS.RESET_DONE.read())) & raw_mask != raw_mask) {}
```

I made some tests using such fix and also can confirm that without fix everytings works in `Debug` build, with fix it works also in `ReleaseSmall` build but doesn't work in `ReleaseFast` and `ReleaseSafe` builds.

**Comment by hryx** [comment]
> `while (@as(u32, @bitCast(RESETS.RESET_DONE.read())) & raw_mask != raw_mask) {}`

Yep, this works for me as you described too. Another alternative suggested by a community member was `hw.tight_loop_contents();` inside the loop body, which also works.
